# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YorGorelease < Formula
  desc "Extensible auto-tagger for your IaC files"
  homepage "https://www.yor.io"
  version "0.1.88-12"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.88-12/yor_0.1.88-12_darwin_amd64.tar.gz"
      sha256 "90cdf4c6e128295319c47d4bd45952d5dca7ff7fba0b98e8ed3af7f23bdd6b5e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.88-12/yor_0.1.88-12_linux_amd64.tar.gz"
      sha256 "18cdebf38b412d076ed29d8d5ca49f89a86bb1ccbf4a5204ac3c0d051668b3c8"
    end
  end

  def install
    bin.install "yor"
  end

  test do
    system "#{bin}/yor", "--help"
  end
end
