# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YorGoreleaser < Formula
  desc "Extensible auto-tagger for your IaC files"
  homepage "https://www.bridgecrew.io"
  version "0.1.85-7"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.85-7/yor-0.1.85-7-darwin-amd64.tar.gz"
      sha256 "5827778c14f3efc3773df4a93f03bb0192fc0b9f7f1b4d320145bf2bf3c1c341"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.85-7/yor-0.1.85-7-darwin-amd64.tar.gz"
      sha256 "a601a90aba34878ab52da32e275d8e27a2ebac35f82b47a6bcba8f54e420cd67"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.85-7/yor-0.1.85-7-darwin-amd64.tar.gz"
      sha256 "5cfdffed160b6884060b458eabb950352268d830043b7ab271d02699048cdf09"
    end
  end

  def install
    bin.install "yor"
  end

  test do
    system "#{bin}/yor", "--help"
  end
end
