# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YorGorelease < Formula
  desc "Extensible auto-tagger for your IaC files"
  homepage "https://www.yor.io"
  version "0.1.88-22"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.88-22/yor_0.1.88-22_darwin_amd64.tar.gz"
      sha256 "8900600c344263edc376bd0ed5e7f2e2b9724daf9b570dc5b27178504b051588"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.88-22/yor_0.1.88-22_linux_amd64.tar.gz"
      sha256 "76ae01e6b8cbd217b1fdf8320b443b65130f87c87d441346f84a2ef184b8e401"
    end
  end

  def install
    bin.install "yor"
  end

  test do
    system "#{bin}/yor", "--help"
  end
end
