# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yor < Formula
  desc "Extensible auto-tagger for your IaC files"
  homepage "https://www.yor.io"
  version "0.1.90"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.90/yor_0.1.90_darwin_amd64.tar.gz"
      sha256 "f941db5784f7754d9ec1aa993e05c21ea059a50425288f82da4e57d6e2eef0f4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.90/yor_0.1.90_linux_amd64.tar.gz"
      sha256 "84b05d4a87236700c4293300e2ae234ee830012caab738cbf576dfcc460f7790"
    end
  end

  def install
    bin.install "yor"
  end

  test do
    system "#{bin}/yor", "--help"
  end
end
