# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yor < Formula
  desc "Extensible auto-tagger for your IaC files"
  homepage "https://www.yor.io"
  version "0.1.94"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.94/yor_0.1.94_darwin_amd64.tar.gz"
      sha256 "dc5c10a44dd213c5a58921ce423bb16285a6c864280e6574b4de5f50b4e3338e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.94/yor_0.1.94_linux_amd64.tar.gz"
      sha256 "32fa223697a4e789b30656ef95f70487383dc34bee5cf1ff5a5c1b3f725d9ab1"
    end
  end

  def install
    bin.install "yor"
  end

  test do
    system "#{bin}/yor", "--help"
  end
end
