# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yor < Formula
  desc "Extensible auto-tagger for your IaC files"
  homepage "https://www.bridgecrew.io"
  version "0.1.85-6"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.85-6/yor-0.1.85-6-darwin-amd64.tar.gz"
      sha256 "0a209268e7f14b327894ad7c5e88423c6a1fd9f6197bbd0f6fee0635c4648148"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.85-6/yor-0.1.85-6-darwin-amd64.tar.gz"
      sha256 "b570eaaf50b9d075a86804ce457432a1c03bc22a69f3b6892e6377a443dd6ce9"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.85-6/yor-0.1.85-6-darwin-amd64.tar.gz"
      sha256 "8b656473618e1a9729a186858fb83af1df12c8bb207df84938c33306bf8ca48e"
    end
  end

  def install
    bin.install "yor"
  end

  test do
    system "#{bin}/yor", "--help"
  end
end
